### PR TITLE
Implemented dummy login and reformatted navigation

### PR DESCRIPTION
**Pull request by merekorlowski**

### CODE REVIEW

**Comment by mmayen** [comment]
so i run the client and nothing shows up its just blank

**Comment by mmayen** [comment]
screen shot 2018-03-13 at 1 42 11 pm

also see these errors

**Comment by merekorlowski** [comment]
Did you make sure to run npm install?

**Comment by mmayen** [comment]
just realized i didnt sorry

**Comment by merekorlowski** [comment]
No problem, let me know if it works.

**Comment by mmayen** [comment]
its still blank on mine

Can someone else please try to run  the client on their system @Opeoluwa112 @karim2506 @preciousO

**Comment by merekorlowski** [comment]
Think I fixed it, try again.

**Comment by mmayen** [comment]
it looks great did you make any dummy login data?

**Pull request merged**
